### ISSUE TITLE
Check for the arm64 installation of Homebrew

### ISSUE THREAD

**Issue by artun42** [ohaiibuzzle/Harbor#2]
They conflict with each other. I can suggest renaming /opt/Homebrew to something else for the time of compilation and changing directory name after compilation is complete to eliminate conflicts of Intel's and AS' versions of brew. I didn't test this but you can try and put this in your terminal script if it works.

**Comment by ohaiibuzzle** [comment]
The issues is that brew insists that you use its x86_64 copy when installing formulas that are x86_64 only, it seems.
Trying to do it anyway results in this fun error messages:

<img width="682" alt="image" src="https://github.com/ohaiibuzzle/Harbor/assets/23693150/75431ab6-4823-4736-9d96-d59a8e91e177">


Renaming /opt/homebrew should also be avoided as well since users *may* have apps already installed
