### ISSUE TITLE
version for Ventura?

### ISSUE THREAD

**Issue by DaveFlashNL** [ohaiibuzzle/Harbor#5]
if it's possible ofcourse

**Comment by ohaiibuzzle** [comment]
@DaveFlashNL Theoretically possible because some people have reported GPTK working (although incomplete) under Ventura 13.3 or later.
However:
* I've somehow managed to already use Sonoma specific features in Harbor to the point where it would actually take effort to roll it down to macOS 13
* Even then app compatibility seems kinda eeeeeeh so like... not the ideal version to be on
